---
title: "Cue React Bx Analysis"
author: "Brendan Cullen"
date: "`r Sys.Date()`"
output:
  html_document:
    code_folding: hide
    highlight: tango
    theme: united
    toc: true
    toc_float: 
      collapsed: TRUE
      smooth_scroll: TRUE
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning= FALSE)

# clear the workspace
rm(list=ls())

```


```{r load packages, include=FALSE}
library(tidyr)
library(dplyr)
library(ggplot2)
library(psych)
library(knitr)
library(stringr)
library(wesanderson)
library(Hmisc)
```

# Import data
```{r import data}
file_dir = "~/Desktop/REV_BxData/data/React/desire_ratings"
sub_pattern = "REV[0-9]{3}"
file_pattern = paste0(sub_pattern, "_taskData_React*")
file_list = list.files(file_dir, pattern = file_pattern)

# import data in long format
for (file in file_list) {
  # if the merged dataset doesn't exist, create it
  if (!exists('dataset')) {
  dataset = read.csv(file.path(file_dir, file), header = FALSE)
  ID = rep(substr(file, 1, 6), nrow(dataset)) # create ID var from first 6 chars of file name
  acq = rep(substr(file, 22, 22), nrow(dataset)) # create acq var from acq number in file name
  dataset = cbind(ID, acq, dataset) # add ID and acq vars to dataframe
  colnames(dataset) = c("ID", "acq", "condition", "trial", "desire_rating")
  }
  
  # if the merged dataset does exist, append to it
  else {
  tmp = read.csv(file.path(file_dir, file), header = FALSE)
  ID = rep(substr(file, 1, 6), nrow(tmp)) # create ID var from first 6 chars of file name
  acq = rep(substr(file, 22, 22), nrow(tmp)) # create acq var from acq number in file name
  tmp = cbind(ID, acq, tmp) # add ID and acq vars to dataframe
  colnames(tmp) = c("ID", "acq", "condition", "trial", "desire_rating")
  dataset = bind_rows(dataset, tmp)
  rm(tmp)
  }
}

# write dataset to output file
# write.csv(dataset, file=paste(file_dir, "React_desire_ratings_all.csv", sep = "/"), row.names=FALSE)
```

# Plot desire ratings by condition for each time point
```{r Plots}
# create var explicitly labeling image type for each trial
dataset <- dataset %>% 
  mutate(condition = ifelse(condition == 1, "PRC",
                    ifelse(condition == 2, "neutral", NA))) %>% # label conditions
  mutate(condition = factor(condition, levels = c("neutral", "PRC"))) %>% # convert to factor
  filter(acq == 1 | acq == 2) # select only baseline data 

# plot desire ratings by image type
ggplot(dataset, aes(condition, desire_rating)) +
  geom_boxplot() +
  geom_jitter(aes(color = condition), alpha = .05) +
  labs(x = "Condition", y = "Desire rating", title = "Boxplot of desire ratings for Neutral vs. PRC trials")

# plot desire ratings by image type for each acq separately 
ggplot(dataset, aes(condition, desire_rating)) +
  geom_boxplot() +
  geom_jitter(aes(color = condition), alpha = .05) +
  facet_wrap(~acq) +
  labs(x = "Condition", y = "Desire rating", title = "Boxplot of desire ratings for Neutral vs. PRC trials \n (by acquisition)")
```

#Plots for publication
```{r Plot for publication}
cbPalette <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")

(desire_ratings_plot <- dataset %>%
  ggplot(aes(condition, desire_rating, fill = condition)) +
    stat_summary(fun.y = mean, geom = "bar") +
    stat_summary(aes(group = ID), fun.y = mean, geom = "point", alpha = .05) +
    stat_summary(aes(group = ID), fun.y = mean, geom = "line", alpha = .05) +
    stat_summary(fun.data = mean_cl_boot, geom = "errorbar", width = 0) + 
    scale_fill_manual(name = "", values = cbPalette) +
    labs(x = "", y = "Mean desire rating") + 
    theme_minimal(base_size = 12) +
    theme(axis.line = element_line(colour = "black"),
          legend.position = "none",
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.border = element_blank(),
          panel.background = element_blank()))

# verify standard errors are correct (they look super small)
standard_error <- dataset %>% 
  group_by(condition) %>% 
  summarise(se = sd(desire_rating, na.rm = TRUE)/sqrt(length(desire_rating)))
```

```{r Save plot}
ggsave(filename = "~/Dropbox/FYP/Figures/Plots/desire_ratings.png", plot = desire_ratings_plot, width = 5, height = 4, dpi = 300)
```


# Stats
```{r t-test}
model <- lme4::lmer(desire_rating ~ condition + (1| ID), data = dataset)
summary(model)
confint(model)
```
 

 