---
title: 'List of React runs and IDs to exclude from analyses'
author: 'Brendan Cullen (adapted from Krista DeStasio)'
date: '11/15/2018'
output:
  html_document:
    toc: yes
    toc_depth: 3
    toc_float: no
  pdf_document:
    toc: yes
    toc_depth: '3'
  word_document:
    toc: yes
    toc_depth: '3'
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
## R version 3.4.3 ##
rm(list = ls())
setwd('~/Desktop/REV_scripts/behavioral/React/scripts/analyses/')
output_dir = '~/Desktop/REV_scripts/behavioral/React/output/'

## Install and load required packages
list.of.packages <- c('reshape2', 'knitr', 'gridExtra', 'ggplot2', 'dplyr')
new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[,'Package'])] 
if (length(new.packages)) install.packages(new.packages, repos = 'http://cran.us.r-project.org') 
lapply(list.of.packages, library, character.only = TRUE)

knitr::opts_chunk$set(fig.width = 12, fig.height = 8, fig.path = 'Figs/', echo = TRUE, warning = FALSE, message = FALSE)
```

```{r Create the participant ID and condition variables, include=FALSE}
ID <- as.factor(c(1:144)) # Create the subject ID column
cond <- c(0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0) # Match the participant to their condition
condition <- factor(cond, labels = c('Control', 'Training'))
```


```{r Read in the data, include=FALSE}
# Counts
df_NoResponseTotal <- read.table(paste0(output_dir, 'React_NoResponse_Count.txt')) 

# Name the columns by the run number
names(df_NoResponseTotal) <- c('run1', 'run2', 'run3', 'run4')

# Append the participant IDs and conditions
df_NoResponseTotal <- cbind(ID, condition, df_NoResponseTotal)

# Convert to long format
df_NoResponseTotal_long <-melt(data = df_NoResponseTotal, idvars = ID, measure.vars = c('run1', 'run2','run3', 'run4'), variable.name = 'run_number')

names(df_NoResponseTotal_long)[4] <- "NoResponseCount"
```
   
   
```{r Plots}
NoResponse_plot <- ggplot(subset(df_NoResponseTotal_long, run_number %in% c('run1', 'run2', 'run3', 'run4'))) +
    aes(x = run_number, y = NoResponseCount, label = ID) +
    geom_point(na.rm = TRUE) +
    geom_text(aes(label = as.character(ID)),hjust = 0, vjust = 0, na.rm = TRUE) +
    ggtitle('No Response Count All Runs \nRaw Data, All Participants')
NoResponse_plot
```
   

```{r}
# identify runs and IDs that have > 5 non-responses
df_NoResponseTotal_long_no_outliers <- df_NoResponseTotal_long %>%
  filter(NoResponseCount <= 5 | NoResponseCount == "NaN") 

omitted_runs <- subset(df_NoResponseTotal_long, !(NoResponseCount %in% df_NoResponseTotal_long_no_outliers$NoResponseCount)) %>%
  select(-condition)

write.csv(omitted_runs, (paste0(output_dir, "/omitted_runs_no_reponses.csv", sep="")), row.names = FALSE)
```