---
title: "make_subject_betas_React"
author: "Brendan Cullen"
date: "11/26/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# clear workspace
rm(list=ls())
```

# load packages
```{r}
library(tidyverse)
```

# specify task info
```{r}
num_trials <- 26
num_rating_reg <- 1
num_motion_regs <- 5

# Specify Fx model subject lists (from REV_React_subject_list.xlsm in Dropbox)
acq1onlyIDs <- c("REV014","REV019","REV116","REV122","REV124")

acq2onlyIDs <- "REV064"

bothacqsIDs <- c("REV001","REV002","REV003","REV005","REV006","REV010","REV011","REV012","REV013","REV015","REV016","REV017","REV018","REV020","REV021","REV022","REV023","REV024","REV029","REV030","REV031","REV032","REV033","REV035","REV036","REV037","REV038","REV039","REV040","REV041","REV042","REV043","REV044","REV045","REV046","REV047","REV048","REV049","REV050","REV051","REV052","REV053","REV054","REV055","REV056","REV057","REV059","REV060","REV062","REV063","REV065","REV067","REV068","REV069","REV070","REV072","REV073","REV074","REV075","REV076","REV077","REV078","REV079","REV080","REV082","REV084","REV085","REV086","REV088","REV089","REV090","REV091","REV093","REV094","REV095","REV097","REV098","REV100","REV101","REV102","REV104","REV105","REV107","REV108","REV109","REV110","REV111","REV112","REV113","REV114","REV115","REV118","REV119","REV120","REV121","REV125","REV126","REV127","REV128","REV129","REV130","REV131","REV132","REV134","REV135","REV136","REV137","REV138","REV140","REV141","REV142","REV144")
```

# import data
```{r}
data <- read.csv('~/Desktop/REV_BxData/data/React/desire_ratings/React_desire_ratings_all.csv') %>% 
  mutate(beta = rep(NA, length(ID))) %>% # create empty placeholder variable
  filter(acq == 1 | acq == 2) %>% # select only baseline data
  select(-desire_rating) # get rid of desire rating variable (not needed)

# convert ID var to character
data$ID <- as.character(data$ID)

# specify name of corresponding beta map for each trial
for (i in 1:nrow(data)) {
  if (data$acq[i] == 1 && data$ID[i] %in% bothacqsIDs){
    data$beta[i] = sprintf('beta%04d.nii', data$trial[i])
  } else if (data$acq[i] == 2 && data$ID[i] %in% bothacqsIDs){
    data$beta[i] = sprintf('beta%04d.nii', data$trial[i] + num_trials + num_rating_reg + num_motion_regs)
  } else if (data$acq[i] == 1 && data$ID[i] %in% acq1onlyIDs){
    data$beta[i] = sprintf('beta%04d.nii', data$trial[i])
  } else if (data$acq[i] == 2 && data$ID[i] %in% acq2onlyIDs){ # applies to REV064
    data$beta[i] = sprintf('beta%04d.nii', data$trial[i])
  }
}
```

# group by subject and export .csv file with betas for PRC and Neutral trials
## PRC = 1, Neutral = 2
```{r}
outputDir='~/Desktop/REV_scripts/fMRI/expression_maps/betaseries/subject_beta_info/'

PRC = data %>% 
  arrange(ID, beta) %>% 
  filter(condition == 1, !is.na(beta)) %>%
  group_by(ID) %>% 
  do({
    fname=paste(
      outputDir,
      'PRC_',.$ID[[1]],'.txt',
      sep='')
    write.table(
      .[,"beta"],
      fname,
      quote=F,
      sep='   ',
      row.names=F,
      col.names=F)
    data.frame(file_name=fname)
  })

neutral = data %>% 
  arrange(ID, beta) %>% 
  filter(condition == 2, !is.na(beta)) %>%
  group_by(ID) %>% 
  do({
    fname=paste(
      outputDir,
      'PRC_',.$ID[[1]],'.txt',
      sep='')
    write.table(
      .[,"beta"],
      fname,
      quote=F,
      sep='   ',
      row.names=F,
      col.names=F)
    data.frame(file_name=fname)
  })

all = data %>% 
  arrange(ID, beta) %>% 
  filter(!is.na(beta)) %>%
  group_by(ID) %>% 
  do({
    fname=paste(
      outputDir,
      'PRC_',.$ID[[1]],'.txt',
      sep='')
    write.table(
      .[,"beta"],
      fname,
      quote=F,
      sep='   ',
      row.names=F,
      col.names=F)
    data.frame(file_name=fname)
  })
```


